service: ruby-resizer # NOTE: update this with your service name


provider:
  name: aws
  runtime: ruby2.5


 iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:*"
     Resource: "*"
  

functions:
  resize_image:
    handler: handler.Resizer.imageResizer
    events:
      - s3:
        bucket: taskmaster-images
        event: s3:ObjectCreate: *


resources:
 Resources:
   ResizedImages:
     Type: AWS::S3::Bucket
     Properties:
       BucketName: resized-images
